<?php


//avia pages holds the data necessary for backend page creation
$avia_pages = array( 
	
	array( 'slug' => 'avia', 		'parent'=>'avia', 'icon'=>"hammer_screwdriver.png" , 	'title' =>  'Theme Options' ),
	array( 'slug' => 'layout', 		'parent'=>'avia', 'icon'=>"blueprint_horizontal.png", 	'title' =>  'Layout &amp; Styling'  ),
	array( 'slug' => 'portfolio', 	'parent'=>'avia', 'icon'=>"photo_album.png" , 			'title' =>  'Portfolio' ),
	array( 'slug' => 'contact', 	'parent'=>'avia', 'icon'=>"book_addresses.png" , 		'title' =>  'Contact &amp; <br/>Social Stuff' ),
	array( 'slug' => 'sidebar', 	'parent'=>'avia', 'icon'=>"layout_select_sidebar.png", 	'title' =>  'Sidebar'  ),
	array( 'slug' => 'footer', 		'parent'=>'avia', 'icon'=>"layout_select_footer.png", 	'title' =>  'Footer'  ),
	array( 'slug' => 'templates', 	'parent'=>'templates','icon'=>"page_white_wrench.png", 	'title' =>  'Template Builder'  )
					 
);





/*Frontpage Settings*/


					
$avia_elements[] =	array(	
					"slug"	=> "avia",
					"name" 	=> "Import Dummy Content: Posts, Pages, Categories and Portfolio Entries",
					"desc" 	=> "If you are new to wordpress or have problems creating posts or pages that look like the theme preview you can import dummy posts and pages here that will definitley help to understand how those tasks are done.",
					"id" 	=> "import",
					"type" 	=> "import");
	
$avia_elements[] =	array(	
					"slug"	=> "avia",
					"name" 	=> "Frontpage Settings",
					"desc" 	=> "Select which page to display on your Frontpage. If left blank the Blog will be displayed",
					"id" 	=> "frontpage",
					"type" 	=> "select",
					"subtype" => 'page');
					
$avia_elements[] =	array(	
					"slug"	=> "avia",
					"name" 	=> "And where do you want to display the Blog?",
					"desc" 	=> "Select which page to display as your Blog Page. If left blank no blog will be displayed",
					"id" 	=> "blogpage",
					"type" 	=> "select",
					"subtype" => 'page',
					"required" => array('frontpage','{true}')
					);
					
$avia_elements[] =	array(	
					"slug"	=> "avia",
					"name" 	=> "Logo",
					"desc" 	=> "Upload a logo image, or enter the URL to an image if its already uploaded. The themes default logo gets applied if the input field is left blank<br/>Logo Dimension: 270px * 80px (if your logo is larger you might need to modify style.css to align it perfectly)",
					"id" 	=> "logo",
					"type" 	=> "upload",
					"label"	=> "Use Image as logo");
					
$avia_elements[] =	array(	
					"slug"	=> "avia",
					"name" 	=> "Google Analytics Tracking Code",
					"desc" 	=> "Enter your Google analytics tracking Code here. It will automatically be added to the themes footer so google can track your visitors behaviour.",
					"id" 	=> "analytics",
					"type" 	=> "textarea"
					);
					
					






/*Layout and Styling Settings*/

	
/*
$avia_elements[] =	array(	
					"slug"	=> "layout",
					"name" 	=> "Which general color scheme should be used?",
					"desc" 	=> "You can choose between a light and a dark color scheme here.",
					"id" 	=> "stylesheet",
					"type" 	=> "select",
					"std" 	=> "light-skin.css",
					"target" => array("default_slideshow_target::.live_bg_default::set_id"),
					"subtype" => array('Light (light-skin.css)'=>'light-skin.css','Minimal (minimal-skin.css)'=>'minimal-skin.css','Dark (dark-skin.css)'=>'dark-skin.css'));
*/

$avia_elements[] =	array(	
					"slug"	=> "layout",
					"id" 	=> "default_slideshow_target",
					"type" 	=> "target",
					"std" 	=> "
					<style type='text/css'>
						.live_bg, .live_bg_default{padding:2%; width:46%; float:left; height:150px;}
					
						.live_bg_default{background:#fff;color:#777;}
						.live_bg_default h3{color:#333;}
						.live_bg_default#dark-skin-css{background:#222;color:#fff;}
						.live_bg_default#dark-skin-css h3{color:#fff;}
						
						
					</style> 
					<div class='live_bg_default'><h3>Demo heading</h3><p>This is default content with a default heading. Font color and text are set based on the skin you choose above. Headings and link colors can be choosen below. <br/> <a class='a_link' href='#'>A link</a> <!--  <a class='an_activelink' href='#'>A hovered link</a>--></p></div>
					
					<div class='live_bg'><h3>Demo heading</h3><p>This is text on a colored background, as for example in your footer.</p><p>Text and <a href='#'>links</a> got the same color, headings are a little lighter</p></div>
					",
					"nodescription" => true
					);	
	
					
$avia_elements[] =	array(	
					"slug"	=> "layout",
					"name" 	=> "Primary color",
					"desc" 	=> "Choose a primary color for the footer background, links, buttons, list items etc (secondary colors (for hover effects for example) are generated by the theme automatically)",
					"id" 	=> "color_1",
					"type" 	=> "colorpicker",
					"std" 	=> "#333941",
					"target" => array("default_slideshow_target::.live_bg_default .a_link::color", "default_slideshow_target::.live_bg, .live_bg p::background-color"),
					);
					
/*
$avia_elements[] =	array(	
					"slug"	=> "layout",
					"name" 	=> "Secondary color",
					"desc" 	=> "Choose a secondary color for links hover state, buttons hover state, etc'",
					"id" 	=> "color_2",
					"type" 	=> "colorpicker",
					"std" 	=> "#515b63",
					"target" => "default_slideshow_target::.live_bg_default .an_activelink::color",
					);
*/

$avia_elements[] =	array(	
					"slug"	=> "layout",
					"name" 	=> "Font Color on colored background",
					"desc" 	=> "Choose a color for font located on color background'",
					"id" 	=> "color_3",
					"type" 	=> "colorpicker",
					"std" 	=> "#ffffff",
					"target" => "default_slideshow_target::.live_bg h3, .live_bg p, .live_bg a::color",
					);			
					
					
					
$avia_elements[] =	array(	"slug"	=> "layout", "type" => "visual_group_start", "id" => "default_image_settings", "nodescription" => true);
					
$avia_elements[] =	array(	
					"slug"	=> "layout",
					"name" 	=> "Do you want to use a stretched layout or a boxed?",
					"desc" 	=> "The stretched layout expands from the left side of the viewport to the right. if you select boxed you will get additional options for background color and image.",
					"id" 	=> "boxed",
					"type" 	=> "select",
					"std" 	=> "",
					"subtype" => array('Stretched layout'=>'','Boxed Layout'=>'boxed'));
					
$avia_elements[] =	array(	
					"slug"	=> "layout",
					"name" 	=> "Background color",
					"desc" 	=> "Choose a background color for the part that is outside of the 'boxed content'. If you have set a background image bellow you can use the autodetect button to get the color at the edge of the image.",
					"id" 	=> "bg_color",
					"type" 	=> "colorpicker",
					"std" 	=> "#f8f8f8",
					"required" => array('boxed','boxed')
					);
					
$avia_elements[] =	array(	
					"slug"	=> "layout",
					"name" 	=> "Background Image",
					"desc" 	=> "This image will be displayed behind the boxed area",
					"id" 	=> "bg_image",
					"type" 	=> "upload",
					"std" 	=> "",
					"required" => array('boxed','boxed'),
					"label"	=> "Use Image");
			 					
$avia_elements[] =	array(	
					"slug"	=> "layout",
					"name" 	=> "Position of the image",
					"desc" 	=> "",
					"id" 	=> "bg_image_position",
					"type" 	=> "select",
					"std" 	=> "left",
					"required" => array('boxed','boxed'),
					"subtype" => array('Left'=>'left','Center'=>'center','Right'=>'right'));
					
$avia_elements[] =	array(	
					"slug"	=> "layout",
					"name" 	=> "Repeat",
					"desc" 	=> "",
					"id" 	=> "bg_image_repeat",
					"type" 	=> "select",
					"std" 	=> "no-repeat",
					"required" => array('boxed','boxed'),
					"subtype" => array('no repeat'=>'no-repeat','Repeat'=>'repeat','Tile Horizontally'=>'repeat-x','Tile Vertically'=>'repeat-y'));
					
$avia_elements[] =	array(	
					"slug"	=> "layout",
					"name" 	=> "Attachment",
					"desc" 	=> "",
					"id" 	=> "bg_image_attachment",
					"type" 	=> "select",
					"std" 	=> "scroll",
					"required" => array('boxed','boxed'),
					"subtype" => array('Scroll'=>'scroll','Fixed'=>'fixed'));
					
$avia_elements[] =	array(	"slug"	=> "layout", "type" => "visual_group_end", "nodescription" => true);
					
$avia_elements[] =	array(	"name" 	=> "Heading Font",
							"slug"	=> "layout",
							"desc" 	=> "The Font heading utilizes cufon and allows you to use a wide range of custom fonts for your headings",
				            "id" 	=> "font_heading",
				            "type" 	=> "select",
				            "std" 	=> "oswald",
				            "subtype" => array(	'Arvo'=>'arvo',
				            					'Bevan'=>'bevan',
				            					'Cantarell'=>'cantarell',
				            					'Cardo'=>'cardo',
				            					'Droid Sans'=>'droidsans',
				            					'Inconsolata'=>'inconsolata',
				            					'Josefin All Characters'=>'josefine',
				            					'Josefin Common Characters'=>'josefine_small',
				            					'Kreon'=>'kreon',
				            					'Lobster'=>'lobster',
				            					'Molengo'=>'molengo',
				            					'Oswald'=>'oswald',
				            					'Reenie Beanie'=>'reeniebeanie__1.4', //number attached is a font size modifier for very small fonts ( * 1.4)
				            					'Tangerine'=>'tangerine__1.6',
				            					'Vollkorn'=>'vollkorn',
				            					'Yanone Kaffeesatz'=>'yanonekaffeesatz'
				            					));
					
$avia_elements[] =	array(	
					"slug"	=> "layout",
					"name" 	=> "Quick CSS",
					"desc" 	=> "Just want to do some quick CSS changes? Enter them here, they will be applied to the theme. If you need to change major portions of the theme please use the custom.css file.",
					"id" 	=> "quick_css",
					"type" 	=> "textarea"
					);
			
					
			


/*portfolio settings*/

	
$avia_elements[] =	array(		
					"slug"	=> "portfolio",
					"name" 	=> "Enter a page slug that should be used for your portfolio single items",
					"desc" 	=> "For example if you enter 'portfolio-item' the link to the item will be <strong>".get_option('home').'/portfolio-item/post-name</strong><br/><br/>Dont use characters that are not allowed in urls and make sure that this slug is not used anywere else on your site (for example as a category or a page)',
					"id" 	=> "portfolio-slug",
					"std" 	=> "portfolio-item",
					"type" 	=> "text");
					
$itemcount = array('All'=>'-1');
for($i = 1; $i<101; $i++) $itemcount[$i] = $i;		
	
$avia_elements[] =	array(	
				"slug"			=> "portfolio",
				"type" 			=> "group", 
				"id" 			=> "portfolio", 
				"linktext" 		=> "Add another Slide",
				"deletetext" 	=> "Remove Slide",
				"blank" 		=> true, 
				"nodescription" => true,
				'subelements' 	=> array(	
						
						array(	"name" 	=> "Which categories should be used for the portfolio?",
								"desc" 	=> "You can select multiple categories here. The Portfolio Page that you choose below will then show all posts from those categories, along with a sort option for each category.",
					            "id" 	=> "portfolio_cats",
					            "type" 	=> "select",
								"slug"	=> "portfolio",
	            				"multiple"=>6,
	            				"taxonomy" => "portfolio_entries",
					            "subtype" => "cat"),
					            
					    							
						array(	"name" 	=> "Which page should display the portfolio?",
								"slug"	=> "portfolio",
								"desc" 	=> "",
					            "id" 	=> "portfolio_page",
					            "type" 	=> "select",
					            "subtype" => "page"),
					            
						array(	
								"slug"	=> "portfolio",
								"name" 	=> "Portfolio Columns",
								"desc" 	=> "How many columns should be displayed?",
								"id" 	=> "portfolio_columns",
								"type" 	=> "select",
								"std" 	=> "4",
								"subtype" => array('1'=>'1','2'=>'2','3'=>'3','4'=>'4')),
								
						array(	
								"slug"	=> "portfolio",
								"name" 	=> "Portfolio Style",
								"desc" 	=> "How should the entries be displayed?",
								"id" 	=> "portfolio_style",
								"type" 	=> "select",
								"std" 	=> "portfolio_entries_boxed",
								"subtype" => array('Boxed'=>'portfolio_entries_boxed','Open'=>'portfolio_entries_open')),
								
						array(	
								"slug"	=> "portfolio",
								"name" 	=> "Portfolio Post Number",
								"desc" 	=> "How many items should be displayed per page?",
								"id" 	=> "portfolio_item_count",
								"type" 	=> "select",
								"std" 	=> "16",
								"subtype" => $itemcount),
								
						array(	
								"slug"	=> "portfolio",
								"name" 	=> "Portfolio Excerpt",
								"desc" 	=> "Should a small text excerpt of the portfolio entry be displayed?",
								"id" 	=> "portfolio_text",
								"type" 	=> "select",
								"std" 	=> "yes",
								"no_first"=>true,
								"subtype" => array('yes'=>'yes','no'=>'no')),	
								
						array(	
								"slug"	=> "portfolio",
								"name" 	=> "Portfolio Pagination",
								"desc" 	=> "Should a portfolio pagination be displayed?",
								"id" 	=> "portfolio_pagination",
								"type" 	=> "select",
								"std" 	=> "yes",
								"no_first"=>true,
								"subtype" => array('yes'=>'yes','no'=>'no'))
	
				)
			);
	



/*Contact + social stuff*/


			
$avia_elements[] =	array(	
			"name" 	=> "Contact Form Page",
			"slug"	=> "contact",
			"desc" 	=> "Select which page should be used to display your contact form.",
			"id" 	=> "email_page",
			"type" 	=> "select",
			"subtype" => 'page');
			
$avia_elements[] =	array(	
			"name" 	=> "Your email adress",
			"slug"	=> "contact",
			"desc" 	=> "Enter the Email adress where mails should be delivered to. (default is '".get_option('admin_email')."')",
			"id" 	=> "email",
			"std" 	=> get_option('admin_email'),
			"type" 	=> "text");
	
$avia_elements[] =	array(	
			"name" 	=> "Your twitter account",
			"slug"	=> "contact",
			"desc" 	=> "Enter your twitter account name. If you leave this blank the twitter link in the head and footer of your site wont be displayed.",
			"id" 	=> "twitter",
			"std" 	=> "envato",
			"type" 	=> "text");
			
$avia_elements[] =	array(	
			"name" 	=> "RSS feed url",
			"slug"	=> "contact",
			"desc" 	=> "If you want to use a service like feedburner enter the feed url here. Otherwise the default wordpress feed url will be used",
			"id" 	=> "feedburner",
			"std" 	=> "",
			"type" 	=> "text");
			
$avia_elements[] =	array(
			"name" 	=> "Your facebook page/group/account",
			"desc" 	=> "Enter the url to your facebook page/group/account. If you leave this blank the facebook link in the head and footer of your site wont be displayed.",
			"id" 	=> "facebook",
			"slug"	=> "contact",
			"std" 	=> "http://www.facebook.com/kriesi.at",
			"type" 	=> "text");
			
			



/*sidebar settings*/
					
$avia_elements[] =	array(	"name" => "Add new widget areas for pages and categories:",
							"desc" => "Here you can add widget areas for single pages or categories. that way you can put different content for each page/category into your sidebar.
After you have choosen the Pages and Categorys which should recieve a unique widget area press the 'Save Changes' button and then start adding widgets to the new widget areas <a href='widgets.php'>here</a>.
<br/><br/>
<strong>Attention when removing areas:</strong> You have to be carefull when deleting widget areas that are not the last one in the list.
It is recommended to avoid this. If you want to know more about this topic please read the documentation that comes with this theme.",
							"id" => "widgetdescription",
							"std" => "",
							"slug"	=> "sidebar",
							"type" => "heading",
							"nodescription"=>true);
			
			
					
$avia_elements[] =	array(	"slug"	=> "sidebar", "type" => "visual_group_start", "id" => "sidebar_left", "class"=>"avia_one_half avia_first", "nodescription" => true);
$avia_elements[] =	array(
					"type" 			=> "group", 
					"id" 			=> "widget_pages", 
					"slug"			=> "sidebar",
					"linktext" 		=> "Add another widget",
					"deletetext" 	=> "Remove widget",
					"blank" 		=> true, 
					"nodescription" => true,
					'subelements' 	=> array(	
	
							array(	
								"name" 	=> "Select a PAGE that should recieve a new widget area:",
								"desc" 	=> "",
								"id" 	=> "widget_page",
								"type" 	=> "select",
								"slug"	=> "sidebar",
								"subtype" => 'page'),				           
						        )   
						);
$avia_elements[] =	array(	"slug"	=> "sidebar", "type" => "visual_group_end", "nodescription" => true);





$avia_elements[] =	array(	"slug"	=> "sidebar", "type" => "visual_group_start", "id" => "sidebar_right", "class"=>"avia_one_half", "nodescription" => true);
$avia_elements[] =	array(
					"type" 			=> "group", 
					"slug"			=> "sidebar",
					"id" 			=> "widget_categories", 
					"linktext" 		=> "Add another widget",
					"deletetext" 	=> "Remove widget",
					"blank" 		=> true, 
					"nodescription" => true,
					'subelements' 	=> array(
						
							array(	
								"name" 	=> "Select a Category that should recieve a new widget area:",
								"desc" 	=> "",
								"id" 	=> "widget_cat",
								"slug"	=> "sidebar",
								"type" 	=> "select",
								"subtype" => 'cat'),				           
						        )   
						);
$avia_elements[] =	array(	"slug"	=> "sidebar", "type" => "visual_group_end", "nodescription" => true);
	





/*footer settings*/

$avia_elements[] =	array(	
					"slug"	=> "footer",
					"name" 	=> "Footer Columns",
					"desc" 	=> "How many colmns should be diplayed in your footer",
					"id" 	=> "footer_columns",
					"type" 	=> "select",
					"std" 	=> "5",
					"subtype" => array('1'=>'1','2'=>'2','3'=>'3','4'=>'4','5'=>'5'));	

$avia_elements[] =	array(	
					"slug"	=> "footer",
					"name" 	=> "Footer Textarea",
					"desc" 	=> "Enter some text at the end of your footer.",
					"id" 	=> "footer_text",
					"type" 	=> "textarea",
					"std"	=> "<a href='#top'><img src ='".AVIA_BASE_URL."images/logo.png' alt=''/></a>Hi there! I’m a bike messenger by day, aspiring actor by night, and this is my blog. I live in Los Angeles, have a great dog named Jack, and I like piña coladas. (And gettin’ caught in the rain). By the way: you can easily edit or remove this logo &amp; text in your wordpress backend, just in case you are wondering :)"
					);
					
				
					

######################################################################
# TEMPLATE BUILDER
######################################################################


$avia_elements[] 	=		array(	"name" => "How does this work?",
							"desc" => "
							<p>It only takes a few simple steps to create any number of unique page layouts with the template builder. The description bellow is just a short intro on how it works, you can read more about it in the <a target='_blank' href='http://docs.kriesi.at/".avia_backend_safe_string($this->base_data['prefix'])."/documentation#template_builder'>documentation</a></p>
							<ol>
								<li>First you need to create a new Template by adding a name and hitting the 'Create template' Button</li>
								<li>Next you select your template from the sidebar at the left. Add elements like columns, post snippets, text content and widget areas.</li>
								<li>Once that is done save the changes by hitting 'Save all Changes'</li>
								<li>Now create or edit a page/post and you will notice that you can select your template at the <strong>dynamic templates</strong> section. If you do, it will be applied to the post or page.</li>
							</ol>
							",
							"id" => "template_builder_description",
							"std" => "",
							"type" => "heading",
							"slug" => "templates",
							"nodescription"=>true);


$avia_elements[] 	=	array(	"name" 	=> "Create a new dynamic template",
								"desc" 	=> "Enter a name for your new template, then hit the 'Create template' Button<br/><strong>Please Note:</strong> Allowed characters include: a-z, A-Z, 0-9, space, underscore and dash",
								"label"	=> "Create template",
								"remove_label"=> "remove this template",
								"id" 	=> "template_builder",
								"type" 	=> "create_options_page",
								"slug"  => "templates",
								"template_sortable" => 'avia_sortable',
 								"temlate_parent" => "templates",
								"temlate_icon" => "layout_header_footer_3_mix.png",
								"temlate_default_elements" => array(
										
										array(
										"type" 	=> "dynamical_add_elements",
										"slug"  => 'templates',
										"name" 	=> "Add Elements",
										"desc" 	=> "Select an Element and hit the 'Add Element' Button.<br/>The Element will be added to the template and you will be able to position it via drag and drop",
										"std"	=> "",
										"id"	=> "add_template_option",
										"options_file"		=> /*AVIA_BASE.*/"includes/admin/register-admin-dynamic-options.php"
										)
									)
								);


